# Generated by Django 4.1.4 on 2022-12-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvprof', '0003_cvschool_school_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvlanguage',
            name='Language',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cvskill',
            name='Skill',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cvwork',
            name='Work',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
