# Generated by Django 4.1.4 on 2023-01-04 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvprof', '0004_cvlanguage_language_cvskill_skill_cvwork_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvmodel',
            name='firstskills',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cvmodel',
            name='secondskills',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cvmodel',
            name='skill',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cvmodel',
            name='thirdkills',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
