# Generated by Django 4.1.4 on 2023-01-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvprof', '0005_cvmodel_firstskills_cvmodel_secondskills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvmodel',
            name='education',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cvmodel',
            name='firstlanguage',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cvmodel',
            name='firstwork_experience',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cvmodel',
            name='fourthskills',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cvmodel',
            name='language',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cvmodel',
            name='primaryschool',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cvmodel',
            name='second_experience',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cvmodel',
            name='secondaryschool',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cvmodel',
            name='secondlanguage',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cvmodel',
            name='tertiaryschool',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cvmodel',
            name='third_experience',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cvmodel',
            name='thirdlanguage',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cvmodel',
            name='work_experience',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
