# Generated by Django 4.1.4 on 2023-01-09 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvprof', '0006_cvmodel_education_cvmodel_firstlanguage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CVLanguage',
        ),
        migrations.DeleteModel(
            name='CVSchool',
        ),
        migrations.DeleteModel(
            name='CVSkill',
        ),
        migrations.DeleteModel(
            name='CVWork',
        ),
    ]
