# Generated by Django 4.1.4 on 2023-01-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvprof', '0007_delete_cvlanguage_delete_cvschool_delete_cvskill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvmodel',
            name='workexper_descrip',
            field=models.TextField(null=True),
        ),
    ]
